name = "gcs-worker"
type = "webpack"

account_id = ""
workers_dev = true
compatibility_date = "2022-03-01"

kv_namespaces = [
        { binding = "TOKENS", preview_id = "", id = "" }
]

[vars]
GCS_BUCKET = ""
GCS_KEY = ""
GCS_SECRET = ""

[env.development]
name = "gcs-worker-dev"

[env.production]
kv_namespaces = [
        { binding = "TOKENS", id = "" }
]

